### ISSUE TITLE
docker?

### ISSUE THREAD

**Issue by somedevreally** [zyachel/libremdb#1]
Hi,

are you planning to support docker image? and is there any public instance to check.?

thanks

**Comment by zyachel** [comment]
hey there!  

I know next to nothing about docker. I'd love to learn it but am busy due to exams until July end. :'/  

However, if you can, then feel free to build one! I'll be happy to merge your pull request.  

As for the public instance, there's [libremdb.herokuapp.com](https://libremdb.herokuapp.com/about). I guess I need to make a section in README to make it more apparent.  

But again, if you do know about dockers, do not hesitate to contribute. I'd like one for [my other project](https://github.com/zyachel/quetre/) as well. :p

**Comment by somedevreally** [comment]
public instance does not have search, how do we look up movies/TV
also libremdb.herokuapp.com redirect to about page.

good luck with your exams, it's more important 👍

**Comment by zyachel** [comment]
Yes, there are a lot of missing functionalities. Search is on the [To-do list](https://github.com/zyachel/libremdb#soon). It is, in fact, half done already(along with movie meter).  

The only route working as of now is the movie info page. For example, here's sonic 2 page on:  

- IMDb: https://www.imdb.com/title/tt12412888/  
- libremdb: https://libremdb.herokuapp.com/title/tt12412888/  

I understand that one typically doesn't manually type in URLs. You can automatically redirect IMDb links to libremdb with  [an extension](https://github.com/einaregilsson/Redirector).  
Or you can wait for a couple of months :)  

And thanks!

**Comment by TheFrenchGhosty** [comment]
@somedevreally @zyachel 

I just made an image.

New service coming soon:

https://github.com/zyachel/libremdb

https://github.com/PussTheCat-org/docker-libremdb-quay
https://quay.io/repository/pussthecatorg/libremdb

I have no play in merging it with upstream, I prefer to retain full control on my images.

**Comment by zyachel** [comment]
Thanks a bunch, @TheFrenchGhosty!  
Hopefully this will help those who'd want one.

**Comment by somedevreally** [comment]
@TheFrenchGhosty thanks the image works perfectly

**Comment by TheFrenchGhosty** [comment]
@zyachel Feel free to link to it/recommend it by the way. I'll maintain it for my instance.

**Comment by zyachel** [comment]
@TheFrenchGhosty, I linked your repo in README. Again, thanks for that. :)
