### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by trueauracoral** [zyachel/libremdb#10]
It's nice to be able to search for movies rather than just go to a specific movie you know the imdb id of. I found this api that helps to do that:

https://v2.sg.media-imdb.com/suggests/r/rise%20of%20gru.json

I couldn't find any better ones. Having search lets you find movies you want to look at.

https://www.imdb.com/find?q=sing

**Comment by zyachel** [comment]
that's a neat JSON response! Did you dig into network requests?  
I might try that route if it's good enough for movie info as well instead of the current method of scraping the webpage which costs some milliseconds, and is prone to breakage if IMDb changes their HTML.  

I have all the basic routes(search, movies by genres, popular movies, etc.) half ready but can't complete them as I'm a bit busy.  

as soon as I get time, I'll implement these functionalities(hopefully in two weeks or so).
